services:
  - type: web
    name: ai-agent-final
    runtime: docker
    repo: https://github.com/LUFICR/Ai-Agent-Final
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
