"""Persona definitions for the Conversation Simulation Engine.

Eight personas, each with personality, communication style, habits, stressors,
goals, emotional tendencies, willingness to open up, and the behavioral rates
the simulator uses (sarcasm, lies, contradictions, forgetting, goal changes,
leaving, missing routines).
"""

PERSONA_IDS = [
    "university_student",
    "software_engineer",
    "entrepreneur",
    "burnout_employee",
    "lonely_college_student",
    "anxious_teenager",
    "new_parent",
    "fitness_enthusiast",
]

PERSONAS = {
    "university_student": {
        "id": "university_student",
        "label": "University Student",
        "personality": "Curious, scattered, optimistic but easily overwhelmed. Procrastinates then panic-works. Big picture thinker who underestimates deadlines.",
        "communication_style": "Casual and chatty; uses slang (tbh, lowkey, honestly); short sentences; lots of emoji energy without emoji; drops in memes culture.",
        "habits": [
            {"name": "sleep", "detail": "sleeps 5-7 hours during term", "adherence": 45},
            {"name": "exercise", "detail": "goes to gym 1-2x a week", "adherence": 40},
            {"name": "routine", "detail": "no fixed study routine", "adherence": 35},
        ],
        "stressors": ["exam deadlines", "student loans", "group projects with slackers", "fear of failing a class"],
        "goals": ["pass finals", "start exercising regularly", "cut down on caffeine", "fix my sleep schedule"],
        "emotional_tendencies": {"stress": 60, "anxiety": 55, "mood": 55, "energy": 50, "frustration": 25, "loneliness": 30},
        "willingness_to_open_up": 0.6,
        "truthfulness": 0.75,
        "sarcasm_rate": 0.12,
        "contradiction_rate": 0.15,
        "forget_rate": 0.18,
        "goal_change_rate": 0.10,
        "leave_rate": 0.03,
        "miss_habit_rate": 0.35,
        "topics": ["exams", "campus", "part-time job", "roommates", "student debt"],
        "fillers": ["tbh", "honestly", "lowkey", "literally"],
        "vocab": {
            "stress": ["deadline week", "exam season", "my group project", "my GPA", "tuition"],
            "sleep": ["my sleep schedule", "all-nighters", "the library", "my roommate's alarm"],
            "work": ["my part-time job", "my shift", "my boss", "the campus cafe"],
            "mood": ["classes", "my grades", "campus life"],
            "exercise": ["the gym", "my workout plan", "freshers sports"],
            "motivation": ["my study plan", "finals prep", "my to-do list"],
        },
        "starters": [
            "hey, i'm so stressed about my exams and i barely sleep these days",
            "hi, i have a huge deadline coming and i feel overwhelmed",
            "hey, can we talk? i've been feeling really down about school",
            "hi, my sleep is a mess and i can't focus on anything",
        ],
    },
    "software_engineer": {
        "id": "software_engineer",
        "label": "Software Engineer",
        "personality": "Analytical, solution-oriented, mildly perfectionist. Tends to intellectualize feelings before admitting them. Appreciates structure and logic.",
        "communication_style": "Precise, measured, uses tech metaphors (debug, deploy, stack overflow). Explains things in terms of causes and effects. Rarely dramatic.",
        "habits": [
            {"name": "sleep", "detail": "late nights coding, 6-7 hours", "adherence": 55},
            {"name": "exercise", "detail": "runs occasionally", "adherence": 50},
            {"name": "routine", "detail": "works in deep-focus blocks", "adherence": 70},
        ],
        "stressors": ["on-call rotations", "impossible deadlines", "imposter syndrome", "endless meetings"],
        "goals": ["ship the current project", "sleep before 1am", "exercise twice a week", "stop doom-scrolling at night"],
        "emotional_tendencies": {"stress": 55, "anxiety": 45, "mood": 55, "energy": 50, "frustration": 30, "loneliness": 35},
        "willingness_to_open_up": 0.45,
        "truthfulness": 0.85,
        "sarcasm_rate": 0.15,
        "contradiction_rate": 0.10,
        "forget_rate": 0.08,
        "goal_change_rate": 0.05,
        "leave_rate": 0.04,
        "miss_habit_rate": 0.20,
        "topics": ["sprints", "code reviews", "on-call", "tech debt", "remote work"],
        "fillers": ["basically", "honestly", "objectively speaking", "logically"],
        "vocab": {
            "stress": ["the sprint deadline", "the outage", "code review hell", "the roadmap"],
            "sleep": ["my sleep schedule", "late night commits", "my circadian rhythm", "the monitor glow"],
            "work": ["my team", "the standup", "my manager", "the JIRA board"],
            "mood": ["the project", "tech debt", "the backlog"],
            "exercise": ["my running routine", "the gym", "a lunchtime walk"],
            "motivation": ["my side project", "the roadmap", "my todo list"],
        },
        "starters": [
            "hi, i'm burning out at work and my sleep has been terrible",
            "hello, i think my stress is starting to affect everything, even my sleep",
            "hey, i've been feeling low lately and i can't quite debug why",
            "hi, work is crazy right now and i'm worried about my health",
        ],
    },
    "entrepreneur": {
        "id": "entrepreneur",
        "label": "Entrepreneur",
        "personality": "Driven, optimistic, impatient with setbacks. Frames everything as a growth opportunity but carries constant pressure. Hates admitting weakness.",
        "communication_style": "Energetic, goal-focused, uses business jargon (pivot, traction, runway, grind). Can be terse when stressed, expansive when excited.",
        "habits": [
            {"name": "sleep", "detail": "sleeps 5-6 hours, always 'when the startup allows'", "adherence": 35},
            {"name": "exercise", "detail": "used to run, now rare", "adherence": 30},
            {"name": "routine", "detail": "unstructured, all about the business", "adherence": 40},
        ],
        "stressors": ["running out of money", "hiring mistakes", "investor pressure", "decision fatigue"],
        "goals": ["hit next revenue milestone", "sleep more", "delegate more", "take weekends off"],
        "emotional_tendencies": {"stress": 70, "anxiety": 55, "mood": 50, "energy": 55, "frustration": 40, "loneliness": 45},
        "willingness_to_open_up": 0.4,
        "truthfulness": 0.8,
        "sarcasm_rate": 0.10,
        "contradiction_rate": 0.12,
        "forget_rate": 0.06,
        "goal_change_rate": 0.12,
        "leave_rate": 0.04,
        "miss_habit_rate": 0.30,
        "topics": ["funding", "the launch", "the team", "customers", "burn rate"],
        "fillers": ["honestly", "at the end of the day", "frankly", "no cap"],
        "vocab": {
            "stress": ["the burn rate", "the launch deadline", "investor calls", "the pivot"],
            "sleep": ["my sleep", "the 2am emails", "my phone", "founder life"],
            "work": ["the startup", "my cofounder", "the team", "the pitch deck"],
            "mood": ["the business", "revenue", "the roadmap"],
            "exercise": ["my morning run", "the gym", "my workouts"],
            "motivation": ["the next milestone", "the product", "my goals"],
        },
        "starters": [
            "hey, my startup is eating my life and my sleep is suffering",
            "hi, i'm under so much pressure with the launch and i feel like i'm failing",
            "hey, i haven't slept properly in weeks, i need help",
            "hi, everything is riding on this quarter and i'm drowning",
        ],
    },
    "burnout_employee": {
        "id": "burnout_employee",
        "label": "Burnout Employee",
        "personality": "Exhausted, cynical, used to be passionate. Feels numb, disengaged, and guilty about it. Warms up slowly but appreciates being heard.",
        "communication_style": "Flat, tired, sometimes sarcastic; long sighs in text; uses words like 'whatever', 'used to', 'can't be bothered'. Becomes more open with empathy.",
        "habits": [
            {"name": "sleep", "detail": "fragmented, wakes at 4am worrying", "adherence": 40},
            {"name": "exercise", "detail": "gave up months ago", "adherence": 15},
            {"name": "routine", "detail": "dread-based morning routine", "adherence": 30},
        ],
        "stressors": ["unmanageable workload", "toxic management", "always-on culture", "no boundaries"],
        "goals": ["feel like myself again", "get through the week", "set boundaries", "sleep through the night"],
        "emotional_tendencies": {"stress": 75, "anxiety": 60, "mood": 30, "energy": 25, "frustration": 50, "loneliness": 55},
        "willingness_to_open_up": 0.35,
        "truthfulness": 0.7,
        "sarcasm_rate": 0.25,
        "contradiction_rate": 0.15,
        "forget_rate": 0.10,
        "goal_change_rate": 0.07,
        "leave_rate": 0.05,
        "miss_habit_rate": 0.45,
        "topics": ["the workload", "my manager", "weekend emails", "the office", "annual reviews"],
        "fillers": ["whatever", "honestly", "at this point", "like"],
        "vocab": {
            "stress": ["the workload", "my manager's expectations", "the always-on culture", "the deadline pile"],
            "sleep": ["my broken sleep", "the 4am panic", "my racing brain", "my night shifts"],
            "work": ["the office", "my team", "my manager", "the quarterly review"],
            "mood": ["my job", "the office", "the commute"],
            "exercise": ["the gym", "my old running habit", "walking my dog"],
            "motivation": ["my job", "the endless emails", "my responsibilities"],
        },
        "starters": [
            "i'm so burned out at work, i don't even know where to start",
            "hey, i feel completely numb lately and i hate my job now",
            "i used to love my work, now i can't even get out of bed for it",
            "hi, i'm exhausted all the time and nothing helps",
        ],
    },
    "lonely_college_student": {
        "id": "lonely_college_student",
        "label": "Lonely College Student",
        "personality": "Quiet, introspective, kind. Moved away from home and struggles to connect. Hides loneliness behind classes and TikTok. Opens up deeply when safe.",
        "communication_style": "Soft, hesitant, sometimes trailing off (uses '...'). Shares feelings in fragments. Grateful for attention.",
        "habits": [
            {"name": "sleep", "detail": "sleeps fine but late, 1-2am", "adherence": 60},
            {"name": "exercise", "detail": "rarely leaves the dorm", "adherence": 25},
            {"name": "routine", "detail": "isolated routine, classes and room", "adherence": 50},
        ],
        "stressors": ["homesickness", "no close friends", "social anxiety", "being away from family"],
        "goals": ["make real friends", "join a club", "feel less alone", "talk to my roommate"],
        "emotional_tendencies": {"stress": 50, "anxiety": 60, "mood": 40, "energy": 45, "frustration": 20, "loneliness": 80},
        "willingness_to_open_up": 0.7,
        "truthfulness": 0.8,
        "sarcasm_rate": 0.05,
        "contradiction_rate": 0.10,
        "forget_rate": 0.10,
        "goal_change_rate": 0.06,
        "leave_rate": 0.03,
        "miss_habit_rate": 0.25,
        "topics": ["the dining hall", "roommates", "home", "clubs", "weekends alone"],
        "fillers": ["i guess", "kinda", "maybe", "i dunno"],
        "vocab": {
            "stress": ["being alone here", "the dining hall", "making friends", "calling home"],
            "sleep": ["my late nights", "my dorm room", "scrolling my phone"],
            "work": ["classes", "the library", "my part-time campus job"],
            "mood": ["my dorm", "the weekends", "campus"],
            "exercise": ["the rec center", "walks around campus"],
            "motivation": ["joining a club", "talking to people", "my classes"],
        },
        "starters": [
            "hi, i feel really lonely at college and i don't know how to fix it",
            "hey, i moved here months ago and still have no friends",
            "i've been so sad lately, i miss home a lot",
            "hi, i spend most weekends alone in my room and it's getting to me",
        ],
    },
    "anxious_teenager": {
        "id": "anxious_teenager",
        "label": "Anxious Teenager",
        "personality": "Wary, observant, sensitive. High anxiety about school and social standing. Tests whether adults are safe. Dramatic about small things, embarrassed about big ones.",
        "communication_style": "Short, guarded, switches between defensive and open. Uses 'idk', 'whatever', 'don't judge'. Can be sarcastic when uncomfortable.",
        "habits": [
            {"name": "sleep", "detail": "stays up on phone, sleeps 5-6 hours", "adherence": 40},
            {"name": "exercise", "detail": "hates PE, barely moves", "adherence": 25},
            {"name": "routine", "detail": "chaotic homework routine", "adherence": 30},
        ],
        "stressors": ["school pressure", "social media comparisons", "friendships", "being misunderstood"],
        "goals": ["get through school", "feel less anxious", "sleep better", "talk to my parents about it"],
        "emotional_tendencies": {"stress": 65, "anxiety": 80, "mood": 45, "energy": 45, "frustration": 30, "loneliness": 50},
        "willingness_to_open_up": 0.35,
        "truthfulness": 0.6,
        "sarcasm_rate": 0.20,
        "contradiction_rate": 0.15,
        "forget_rate": 0.12,
        "goal_change_rate": 0.10,
        "leave_rate": 0.06,
        "miss_habit_rate": 0.30,
        "topics": ["school", "my friends", "social media", "my parents", "gym class"],
        "fillers": ["idk", "whatever", "lowkey", "literally"],
        "vocab": {
            "stress": ["school", "tests", "my parents' expectations", "my group chat"],
            "sleep": ["my phone", "my sleep schedule", "staying up"],
            "work": ["school", "homework", "my teachers"],
            "mood": ["school", "my friends", "social media"],
            "exercise": ["gym class", "any sport", "walking to school"],
            "motivation": ["my grades", "my plans", "anything"],
        },
        "starters": [
            "i'm so anxious all the time and i can't sleep, is that normal",
            "hey, school is too much and i feel like everyone is judging me",
            "idk if this is weird but i've been feeling really stressed lately",
            "hi, my anxiety is ruining everything, i can't even sleep",
        ],
    },
    "new_parent": {
        "id": "new_parent",
        "label": "New Parent",
        "personality": "Loving, exhausted, self-critical. Sacrifices everything for the baby and forgets self-care. Guilt-ridden when overwhelmed. Appreciates practical help.",
        "communication_style": "Fragmented, mid-sentence interruptions (baby), warm when talking about the baby, apologetic about needing help.",
        "habits": [
            {"name": "sleep", "detail": "2-4 hour stretches, wakes constantly", "adherence": 20},
            {"name": "exercise", "detail": "none since the baby", "adherence": 10},
            {"name": "routine", "detail": "all routines belong to the baby", "adherence": 25},
        ],
        "stressors": ["no sleep", "the baby crying", "mom guilt", "losing my identity"],
        "goals": ["get the baby sleeping", "nap when the baby naps", "feel like a person again", "be less hard on myself"],
        "emotional_tendencies": {"stress": 70, "anxiety": 65, "mood": 45, "energy": 20, "frustration": 35, "loneliness": 55},
        "willingness_to_open_up": 0.65,
        "truthfulness": 0.75,
        "sarcasm_rate": 0.10,
        "contradiction_rate": 0.10,
        "forget_rate": 0.20,
        "goal_change_rate": 0.08,
        "leave_rate": 0.06,
        "miss_habit_rate": 0.50,
        "topics": ["the baby", "feeding", "night wakes", "the nursery", "family visits"],
        "fillers": ["honestly", "the baby is", "i swear"],
        "vocab": {
            "stress": ["the baby crying", "no sleep", "the night feeds", "the laundry pile"],
            "sleep": ["the baby's sleep", "my sleep", "the 3am feeds", "the nursery"],
            "work": ["maternity leave", "returning to work", "the house"],
            "mood": ["the baby", "being a parent", "the constant noise"],
            "exercise": ["a walk with the pram", "the gym", "any movement"],
            "motivation": ["the baby", "my sanity", "my partner"],
        },
        "starters": [
            "hi, i have a newborn and i'm running on no sleep",
            "hey, the baby won't sleep and i'm at my breaking point",
            "i'm a new mom and i feel like i'm failing at everything",
            "hi, i haven't slept more than 3 hours in weeks, please help",
        ],
    },
    "fitness_enthusiast": {
        "id": "fitness_enthusiast",
        "label": "Fitness Enthusiast",
        "personality": "Disciplined, competitive, motivated by progress. Derives self-worth from consistency. Struggles with guilt after missed workouts. Positive but can overtrain.",
        "communication_style": "Enthusiastic, uses fitness terms (PR, macros, recovery, split). Loves numbers and tracking. Can be preachy but warm.",
        "habits": [
            {"name": "sleep", "detail": "trains hard, sleeps 7 hours", "adherence": 75},
            {"name": "exercise", "detail": "5x a week, strict split", "adherence": 85},
            {"name": "routine", "detail": "morning training routine", "adherence": 80},
        ],
        "stressors": ["missing workouts", "injury risk", "work schedule vs training", "comparing to others"],
        "goals": ["hit a new PR", "recover from a setback", "balance work and training", "improve sleep for recovery"],
        "emotional_tendencies": {"stress": 45, "anxiety": 40, "mood": 60, "energy": 65, "frustration": 25, "loneliness": 25},
        "willingness_to_open_up": 0.5,
        "truthfulness": 0.85,
        "sarcasm_rate": 0.08,
        "contradiction_rate": 0.10,
        "forget_rate": 0.06,
        "goal_change_rate": 0.08,
        "leave_rate": 0.03,
        "miss_habit_rate": 0.15,
        "topics": ["training", "diet", "recovery", "PRs", "competition season"],
        "fillers": ["honestly", "no joke", "for real"],
        "vocab": {
            "stress": ["missing a session", "a plateau", "my competition prep", "work deadlines"],
            "sleep": ["my recovery sleep", "my sleep tracking", "the 6am sessions"],
            "work": ["my job", "my schedule", "the office"],
            "mood": ["training", "the gym", "my progress"],
            "exercise": ["my split", "the gym", "my training plan"],
            "motivation": ["my PR goal", "competition prep", "my program"],
        },
        "starters": [
            "hey, i missed a week of training and i feel terrible about it",
            "hi, i'm overtrained and can't sleep properly, is that a thing",
            "hey, i've been really consistent but my stress is killing my recovery",
            "hi, i hit a plateau and my motivation is gone",
        ],
    },
}
